language: node_js # Building with node js
node_js:
  - stable # Download the stable node version

# Blocklist
branches:
  except:
    - gh-pages # will be deployed to, no need to build it

script:
  - npm run build-deploy # Generates the deployment folder with built angular app and umd bundle

deploy:
  provider: pages
  skip_cleanup: true # Prevent travis from cleaning out the branch before the deploy occurs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master # Build only from master
  local_dir: deployment # Only copy the deployment content
